(ns lobby.view
	(:require 
		[lobby.model :as model]
		[lobby.comms :as comms]))
    
(defn main []
  [:div
		[:div "Generated by ClojureScript"]
		[:div (:data @model/app)]
		[:button.btn {:on-click #(comms/sendone)} "Send Req"]])